---
- hosts: localhost
  vars:
        vcenter_hostname: 10.31.135.10
        vcenter_login: surnins@demo.local
        vcenter_password: P@ssw0rd
        guest_name: newvm02
        guest_ncpus: 2
        guest_memory: 1024
        guest_ip_addr: 10.31.135.108
        guest_ip_netmask: 255.255.255.0
        guest_ip_gateway: 10.31.135.1
        guest_network: dvManagement_VLAN3235
        template: rhel7.5-template
  tasks:
   - name: Create a virtual machine "{{ guest_name }}" from a template "{{ template }}"
     vmware_guest:
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_login }}"
       password: "{{ vcenter_password }}"
       datacenter: Datacenter
       validate_certs: no
       folder: /Surnin
       name: "{{ guest_name }}"
       state: poweredon
       template: "{{ template }}"
       disk:
        - size_gb: 100
          type: thin
          datastore: vsanDatastore
       hardware:
        memory_mb: "{{ guest_memory }}"
        num_cpus: "{{ guest_ncpus }}"
        num_cpu_cores_per_socket: 1
        scsi: paravirtual
#      memory_reservation: 512
#      memory_reservation_lock: True
#      mem_limit: 8096
#      mem_reservation: 4096
#      cpu_limit: 8096
#      cpu_reservation: 4096
#      max_connections: 5
#      hotadd_cpu: True
#      hotremove_cpu: True
#      hotadd_memory: False
#        version: 13 # Hardware version of virtual machine
        boot_firmware: "bios"
       networks:
       - name: "{{ guest_network }}"
         type: static
         ip: "{{ guest_ip_addr }}"
         netmask: "{{ guest_ip_netmask }}"
         gateway: "{{ guest_ip_gateway }}"
#      mac: aa:bb:dd:aa:00:14
       wait_for_ip_address: yes
     delegate_to: localhost
     register: deploy

   - name: Check network connectivity with host "{{ guest_name }}"
     ping:

   - name: Adding host "{{ guest_name }}" with ip "{{ guest_ip_addr }}" to the inventory
     add_host:
       name: "{{ guest_ip_addr }}"
       groups: newvm

- hosts: newvm
  tasks:
    - name: Setup YUM repo
      yum_repository:
       baseurl: https://10.31.135.102/repo
       enabled: yes
       gpgcheck: no
       name: rhel7.5-repo
       repo_gpgcheck: no
       description: rhel7.5-repo
       sslverify: no

    - name: Install postgresql server
      yum:
        name: postgresql-server
        state: installed

    - name: Initialize DB
      shell: postgresql-setup initdb

    - name: Starts the Database and enable autostart
      systemd:
         name: postgresql
         enabled: yes
         state: started