 
  - name: Setup YUM CentOS 7.5 repo
    yum_repository:
      baseurl: http://10.31.135.106/repo
      enabled: yes
      gpgcheck: no
      name: centos7.5-repo-ansctl
      repo_gpgcheck: no
      description: centos7.5-repo
      sslverify: no
    when: internet_access == False


  - name: Add Postgres repo from Web if you have Internet Access
    yum_repository:
      baseurl: https://download.postgresql.org/pub/repos/yum/{{postgresql_version}}/redhat/rhel-latest-x86_64/
      enabled: yes
      gpgcheck: no
      name: Postgres-WEB-Repo 
      repo_gpgcheck: no
      description: Postgres WEB repo
      sslverify: no
    when: internet_access == True


  - name: Disable firewalld service
    systemd:
      name: firewalld
      enabled: no
      state: stopped



