 
  - name: Setup YUM CentOS 7.5 repo
    yum_repository:
      baseurl: http://10.31.135.106/repo
      enabled: yes
      gpgcheck: no
      name: centos7.5-repo-ansctl
      repo_gpgcheck: no
      description: centos7.5-repo
      sslverify: no
#    when: internet_access == False


  - name: Disable firewalld service
    systemd:
      name: firewalld
      enabled: no
      state: stopped


  - name: Install NFS client
    yum:
     name: 
      - nfs-utils
      #- nfs-utils-lib
     state: installed



